export type LegalLocale = "en" | "hi" | "mr";

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDoc {
  title: string;
  lastUpdated: string;
  intro: string;
  sections: LegalSection[];
}

export const PRIVACY: Record<LegalLocale, LegalDoc> = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: 7 Aug 2026",
    intro:
      "Jyotish respects your privacy. This policy explains what we collect, why we collect it, and how we protect it.",
    sections: [
      { heading: "What we collect", body: "Your name, birth date/time/place, mobile number (optional), your chat messages with Arya, a random device ID, and — only if you sign in with Google — your Google email and name." },
      { heading: "AI processing & transparency", body: "All readings and chat replies are generated by an artificial intelligence model (Arya is an AI, not a human astrologer). Your messages are sent to a third-party AI provider to generate replies, and are stored to keep your conversation available to you. Avoid sharing sensitive personal information beyond what is needed for the service." },
      { heading: "How we use it", body: "To generate your Vedic Kundli, give you personalised readings and chat replies, and to keep the service working. We never sell your data." },
      { heading: "Storage & security", body: "Data is stored securely (Supabase) with encryption in transit and database row-level security. Your birth details are sensitive — we treat them as confidential." },
      { heading: "Payments", body: "Payments (e.g. the question pack) are processed by Razorpay. We never see or store your card or UPI credentials." },
      { heading: "Your rights", body: "You can ask us to show or delete your data anytime. Contact us and we'll act within a reasonable time." },
      { heading: "Contact", body: "For privacy questions, contact us at support@aijothis.com." },
    ],
  },
  hi: {
    title: "गोपनीयता नीति",
    lastUpdated: "अंतिम अद्यतन: 7 अगस्त 2026",
    intro:
      "ज्योतिष आपकी गोपनीयता का सम्मान करता है। यह नीति बताती है कि हम क्या एकत्र करते हैं, क्यों, और उसे कैसे सुरक्षित रखते हैं।",
    sections: [
      { heading: "हम क्या एकत्र करते हैं", body: "आपका नाम, जन्म तिथि/समय/स्थान, मोबाइल नंबर (वैकल्पिक), आर्य से आपकी चैट, एक रैंडम device ID, और — केवल Google से login करने पर — आपका Google email और नाम।" },
      { heading: "AI प्रोसेसिंग और पारदर्शिता", body: "सभी वाचन और चैट उत्तर एक आर्टिफिशियल इंटेलिजेंस मॉडल से बनते हैं (आर्य एक AI है, इंसानी ज्योतिषी नहीं)। आपके messages उत्तर बनाने के लिए तीसरे पक्ष के AI प्रदाता को भेजे जाते हैं, और आपकी बातचीत सहेजी जाती है। सेवा के लिए ज़रूरी होने से अधिक संवेदनशील व्यक्तिगत जानकारी साझा न करें।" },
      { heading: "हम इसका उपयोग कैसे करते हैं", body: "आपकी वैदिक कुंडली बनाने, व्यक्तिगत वाचन और चैट जवाब देने, और सेवा चालू रखने के लिए। हम आपका डेटा कभी नहीं बेचते।" },
      { heading: "भंडारण व सुरक्षा", body: "डेटा सुरक्षित रूप से (Supabase) संग्रहीत है — ट्रांज़िट में एन्क्रिप्टेड और डेटाबेस row-level security के साथ। आपकी जन्म जानकारी संवेदनशील है — हम उसे गोपनीय रखते हैं।" },
      { heading: "भुगतान", body: "भुगतान (जैसे question pack) Razorpay द्वारा संसाधित होता है। हम आपके कार्ड या UPI की जानकारी कभी नहीं देखते या संग्रहीत नहीं करते।" },
      { heading: "आपके अधिकार", body: "आप किसी भी समय अपना डेटा दिखाने या हटाने के लिए कह सकते हैं। संपर्क करें — हम उचित समय में कार्रवाई करेंगे।" },
      { heading: "संपर्क", body: "गोपनीयता संबंधी सवालों के लिए: support@aijothis.com।" },
    ],
  },
  mr: {
    title: "गोपनीयता धोरण",
    lastUpdated: "शेवटचे अपडेट: ७ ऑगस्ट २०२६",
    intro:
      "ज्योतिष तुमच्या गोपनीयतेचा आदर करतो. हे धोरण सांगते की आम्ही काय गोळा करतो, का, आणि ते कसे सुरक्षित ठेवतो.",
    sections: [
      { heading: "आम्ही काय गोळा करतो", body: "तुमचे नाव, जन्मतारीख/वेळ/ठिकाण, मोबाईल नंबर (ऐच्छिक), आर्यशी तुमचे संभाषण, एक रँडम device ID, आणि — फक्त Google ने login केल्यास — तुमचा Google email आणि नाव." },
      { heading: "AI प्रक्रिया आणि पारदर्शकता", body: "सर्व वाचन आणि चॅट उत्तरे एका आर्टिफिशियल इंटेलिजन्स मॉडेलद्वारे तयार होतात (आर्य हा AI आहे, माणूस नाही). तुमचे संदेश उत्तर निर्माण करण्यासाठी तृतीय-पक्ष AI प्रदात्याला पाठवले जातात, आणि संभाषण साठवले जाते. सेवेसाठी आवश्यक तेवढीच संवेदनशील माहिती सामायिक करा." },
      { heading: "आम्ही ते कसे वापरतो", body: "तुमची वैदिक कुंडली बनवण्यासाठी, वैयक्तिक वाचन आणि चॅट उत्तरे देण्यासाठी, आणि सेवा सुरू ठेवण्यासाठी. आम्ही तुमचा डेटा कधीही विकत नाही." },
      { heading: "साठवण व सुरक्षा", body: "डेटा सुरक्षितपणे (Supabase) साठवला आहे — ट्रान्झिटमध्ये एन्क्रिप्टेड आणि डेटाबेस row-level security सह. तुमची जन्म माहिती संवेदनशील आहे — आम्ही ती गोपनीय ठेवतो." },
      { heading: "पेमेंट", body: "पेमेंट (जसे question pack) Razorpay द्वारे प्रक्रिया केले जाते. आम्ही तुमचा कार्ड किंवा UPI तपशील कधीही पाहत नाही." },
      { heading: "तुमचे अधिकार", body: "तुम्ही कधीही तुमचा डेटा दाखवण्यासाठी किंवा हटवण्यासाठी विचारू शकता. संपर्क करा — आम्ही योग्य वेळेत कारवाई करू." },
      { heading: "संपर्क", body: "गोपनीयता प्रश्नांसाठी: support@aijothis.com." },
    ],
  },
};

export const TERMS: Record<LegalLocale, LegalDoc> = {
  en: {
    title: "Terms & Conditions",
    lastUpdated: "Last updated: 7 Aug 2026",
    intro:
      "By using Jyotish you agree to these terms. Please read them carefully — especially the parts about AI-generated content and that Arya is not a human astrologer.",
    sections: [
      { heading: "Crisis & emergency notice", body: "IF YOU ARE THINKING ABOUT HARMING YOURSELF OR OTHERS, OR YOU FEEL ANOTHER PERSON MAY BE IN DANGER, OR YOU HAVE A MEDICAL EMERGENCY — STOP USING THE SERVICE AND IMMEDIATELY CONTACT THE POLICE (in India call 112) OR A SUICIDE-PREVENTION HELPLINE SUCH AS AASRA (91-22-27546669), KIRAN (1800-599-0019) OR iCALL (9152987821). THE PLATFORM IS NOT DESIGNED FOR USE IN ANY OF THESE SITUATIONS AND CANNOT PROVIDE THE ASSISTANCE REQUIRED. IF YOU CONTINUE TO USE THE SERVICE IN SUCH A SITUATION, YOU DO SO ENTIRELY AT YOUR OWN RISK." },
      { heading: "The service", body: "Jyotish is an AI Vedic astrology app. It generates your Kundli from the birth details you provide and gives personalised readings and chat replies through Arya, an AI astrologer. Arya is an artificial intelligence (a computer program), not a human astrologer. The service is for entertainment, self-reflection and personal insight." },
      { heading: "AI-generated content", body: "Everything Arya says is generated by artificial intelligence. AI can make mistakes, and readings may be inaccurate, incomplete, or out of date. No human astrologer reviews your reading before it is shown to you. Treat all outputs as AI-generated reference material — not as verified or guaranteed information." },
      { heading: "Not professional advice", body: "Readings are not professional advice. They are not a substitute for the advice of qualified professionals such as doctors, lawyers, financial advisors, relationship counsellors, or mental-health professionals. Do not make major life decisions — marriage, career, money, health, or family — based solely on anything Arya says. Always consult a real human professional for important decisions. The service is not intended for clinical diagnosis or for information about which drugs or medical treatment may be appropriate for you — disregard any such advice given through the service. Do not disregard, avoid, or delay in obtaining in-person care from your doctor or another qualified professional because of information you received from Arya." },
      { heading: "System-generated advice", body: "All readings, chat replies and predictions are system-generated by an interactive AI tool (Arya) and are intended solely for general informational and entertainment purposes. They do not constitute professional, medical, legal, financial or specialised advice. We make no warranties about the accuracy, completeness or applicability of any system-generated advice. Any reliance on Arya's output is entirely at your own risk, and you are encouraged to consult qualified professionals before making any decision based on it." },
      { heading: "Your responsibility", body: "You are responsible for your own decisions. You use the service at your own risk and agree not to rely on readings as fact. If you are in distress or thinking about self-harm, reach out to a trusted person or a mental-health professional (in India: KIRAN 1800-599-0019, or iCall 9152987821)." },
      { heading: "Accounts", body: "You may use the service without an account, or sign in with Google. You must be at least 18 years old and able to enter a legally binding contract under the Indian Contract Act, 1872. Your birth details should be accurate — we compute your chart from them." },
      { heading: "Payments & refunds", body: "Question packs are one-time, non-recurring purchases. Payments are processed by Razorpay. Refunds are available within 7 days of purchase only if the questions remain entirely unused. No refund is given for the accuracy or usefulness of any reading, prediction or advice — astrology is interpretive, not factual, and we take no responsibility for the factual accuracy of any consultation." },
      { heading: "Acceptable use", body: "Don't misuse the service — no abusive, defamatory, harassing or unlawful content; no attempts to harm, disrupt or gain unauthorised access to the service; no use of another person's account or details; no more than one account per person. The service does not facilitate black magic, witchcraft, voodoo, tantric practices or harm to others. Report any misuse or abuse to support@aijothis.com. We may suspend accounts that violate these terms." },
      { heading: "No guarantees", body: "Astrology is interpretive, not factual. We do not guarantee the accuracy of any reading, prediction, or time window, and we make no promise about future events. Predictions are suggestions, not certainties." },
      { heading: "Acknowledgment", body: "By using Jyotish you acknowledge that you understand: (a) Arya is an AI, not a human; (b) all content is AI-generated and may be wrong; (c) the service is for entertainment and reference; (d) it is not professional advice; and (e) you will not rely on it for critical life decisions." },
      { heading: "Liability", body: "To the maximum extent permitted by law, Jyotish is not liable for any decisions, actions, or outcomes based on readings or AI-generated content. Our total liability is limited to the amount you paid for the service." },
      { heading: "How Arya talks (tone & what to expect)", body: "Arya is designed to talk warmly, conversationally and personally — like a trusted friend or elder, not a formal report. Because the service is for entertainment, comfort and self-reflection, she may be encouraging, expressive and direct about emotional topics (love, marriage, family, feelings). This tone is deliberate and is part of the service. By using Jyotish you accept that Arya's conversational style — including engaging warmly on personal topics — is part of what you are signing up for, and you take responsibility for what you choose to share and how you act on anything said. You can end a chat or stop using the service at any time. None of it is professional advice, and every reading is an AI-generated interpretation, not fact (see the sections above)." },
      { heading: "Indemnification", body: "You agree to indemnify and hold harmless Jyotish and its owners, officers, employees and agents from any claims, losses, damages or costs (including legal fees) arising from your use of the service, your violation of these terms, or your misuse of the service." },
      { heading: "Governing law & jurisdiction", body: "These terms are governed by the laws of India. Any dispute arising from these terms shall be resolved by arbitration in New Delhi under the Arbitration and Conciliation Act, 1996, before a single arbitrator, and the award shall be final and binding. You submit to the exclusive jurisdiction of the courts of New Delhi for any interim relief or matters not subject to arbitration." },
      { heading: "Changes & contact", body: "We may update these terms. Continued use after changes means acceptance. Questions: support@aijothis.com." },
    ],
  },
  hi: {
    title: "नियम व शर्तें",
    lastUpdated: "अंतिम अद्यतन: 7 अगस्त 2026",
    intro: "ज्योतिष का उपयोग करने से आप इन नियमों से सहमत होते हैं। कृपया ध्यान से पढ़ें — विशेषकर AI-जनित सामग्री और यह कि आर्य कोई इंसानी ज्योतिषी नहीं है।",
    sections: [
      { heading: "संकट और आपातकालीन सूचना", body: "यदि आप स्वयं को या दूसरों को नुकसान पहुँचाने के विचार में हैं, या आपको लगता है कि कोई अन्य व्यक्ति खतरे में है, या आपके पास कोई चिकित्सा आपातकाल है — सेवा का उपयोग तुरंत बंद करें और तुरंत पुलिस (भारत में 112) या आत्महत्या रोकथाम हेल्पलाइन जैसे AASRA (91-22-27546669), KIRAN (1800-599-0019) या iCall (9152987821) से संपर्क करें। प्लेटफ़ॉर्म इनमें से किसी भी स्थिति में उपयोग के लिए नहीं बना है और आवश्यक सहायता प्रदान नहीं कर सकता। यदि आप फिर भी ऐसी स्थिति में सेवा का उपयोग जारी रखते हैं, तो आप पूरी तरह अपने जोखिम पर ऐसा करते हैं।" },
      { heading: "सेवा", body: "ज्योतिष एक AI वैदिक ज्योतिष ऐप है। यह आपकी जन्म जानकारी से आपकी कुंडली बनाता है और आर्य (एक AI ज्योतिषी) के माध्यम से व्यक्तिगत वाचन और चैट उत्तर देता है। आर्य एक आर्टिफिशियल इंटेलिजेंस (कंप्यूटर प्रोग्राम) है, इंसान नहीं। सेवा मनोरंजन, आत्म-चिंतन और व्यक्तिगत जानकारी के लिए है।" },
      { heading: "AI-जनित सामग्री", body: "आर्य जो कुछ भी कहता है वह आर्टिफिशियल इंटेलिजेंस से बनता है। AI गलतियाँ कर सकता है — वाचन गलत, अधूरा या पुराना हो सकता है। आपका वाचन दिखाने से पहले कोई इंसान उसकी समीक्षा नहीं करता। सभी आउटपुट को AI-जनित संदर्भ सामग्री मानें — सत्यापित या गारंटीकृत जानकारी नहीं।" },
      { heading: "पेशेवर सलाह नहीं", body: "वाचन पेशेवर सलाह नहीं है। यह डॉक्टर, वकील, वित्तीय सलाहकार, रिश्ता परामर्शदाता या मानसिक स्वास्थ्य विशेषज्ञ की सलाह का विकल्प नहीं है। महत्वपूर्ण जीवन निर्णय — शादी, करियर, धन, स्वास्थ्य, परिवार — केवल आर्य की बात पर न लें। हमेशा किसी वास्तविक इंसानी विशेषज्ञ से सलाह लें। सेवा चिकित्सकीय निदान या यह बताने के लिए नहीं है कि आपके लिए कौन सी दवा या उपचार उचित है — सेवा के माध्यम से दी गई ऐसी कोई सलाह मानें नहीं। आर्य से मिली जानकारी के कारण अपने डॉक्टर या किसी योग्य पेशेवर से व्यक्तिगत (in-person) देखभाल लेने में देरी, टालमटोल या उपेक्षा न करें।" },
      { heading: "सिस्टम-जनित सलाह", body: "सभी वाचन, चैट उत्तर और भविष्यवाणियाँ एक इंटरैक्टिव AI टूल (आर्य) द्वारा सिस्टम-जनित हैं और केवल सामान्य सूचना और मनोरंजन के उद्देश्य से हैं। ये पेशेवर, चिकित्सा, कानूनी, वित्तीय या विशेषज्ञ सलाह नहीं हैं। हम किसी सिस्टम-जनित सलाह की सटीकता, पूर्णता या प्रयोज्यता की कोई गारंटी नहीं देते। आर्य के आउटपुट पर कोई भी निर्भरता पूरी तरह आपके अपने जोखिम पर है, और उसके आधार पर कोई भी निर्णय लेने से पहले आपको योग्य पेशेवरों से सलाह लेने के लिए प्रोत्साहित किया जाता है।" },
      { heading: "आपकी ज़िम्मेदारी", body: "आप अपने निर्णयों के लिए स्वयं ज़िम्मेदार हैं। आप अपने जोखिम पर सेवा उपयोग करते हैं और वाचन को तथ्य नहीं मानने से सहमत हैं। यदि आप संकट में हैं या आत्महत्या के विचार कर रहे हैं, तो किसी भरोसेमंद व्यक्ति या मानसिक स्वास्थ्य पेशेवर से संपर्क करें (भारत में: KIRAN 1800-599-0019, या iCall 9152987821)।" },
      { heading: "खाते", body: "आप बिना खाते के सेवा उपयोग कर सकते हैं, या Google से login कर सकते हैं। आयु कम से कम 18 वर्ष होनी चाहिए और आप भारतीय अनुबंध अधिनियम, 1872 के तहत कानूनी रूप से बाध्यकारी अनुबंध करने में सक्षम होने चाहिए। जन्म विवरण सही होना चाहिए — हम उससे आपकी कुंडली बनाते हैं।" },
      { heading: "भुगतान व रिफंड", body: "Question packs एक बार की, गैर-आवर्ती खरीद हैं। भुगतान Razorpay द्वारा होता है। खरीद के 7 दिनों के भीतर रिफंड केवल तभी उपलब्ध है जब questions पूरी तरह अनुपयोगी हों। किसी भी वाचन, भविष्यवाणी या सलाह की सटीकता या उपयोगिता के लिए कोई रिफंड नहीं दिया जाता — ज्योतिष व्याख्यात्मक है, तथ्यात्मक नहीं, और हम किसी भी परामर्श की तथ्यात्मक सटीकता की ज़िम्मेदारी नहीं लेते।" },
      { heading: "उचित उपयोग", body: "सेवा का दुरुपयोग न करें — कोई अपमानजनक, मानहानिकारक, परेशान करने वाली या गैरकानूनी सामग्री नहीं; सेवा को नुकसान पहुँचाने, बाधित करने या अनधिकृत पहुँच के प्रयास नहीं; किसी अन्य व्यक्ति के खाते या विवरण का उपयोग नहीं; प्रति व्यक्ति एक से अधिक खाता नहीं। सेवा काला जादू, जादू-टोना, वूडू, तांत्रिक प्रथाओं या दूसरों को नुकसान की सुविधा नहीं देती। किसी भी दुरुपयोग की सूचना support@aijothis.com पर दें। नियम तोड़ने पर खाते निलंबित किए जा सकते हैं।" },
      { heading: "कोई गारंटी नहीं", body: "ज्योतिष व्याख्यात्मक है, तथ्यात्मक नहीं। हम किसी वाचन, भविष्यवाणी या समय-सीमा की सटीकता की गारंटी नहीं देते और भविष्य की घटनाओं का कोई वादा नहीं करते। भविष्यवाणियाँ सुझाव हैं, निश्चितताएँ नहीं।" },
      { heading: "स्वीकृति", body: "ज्योतिष उपयोग करने से आप स्वीकार करते हैं कि आप समझते हैं: (क) आर्य एक AI है, इंसान नहीं; (ख) सभी सामग्री AI-जनित है और गलत हो सकती है; (ग) सेवा मनोरंजन और संदर्भ के लिए है; (घ) यह पेशेवर सलाह नहीं है; और (ङ) आप इस पर महत्वपूर्ण जीवन निर्णय नहीं लेंगे।" },
      { heading: "दायित्व", body: "कानून द्वारा अनुमत अधिकतम सीमा तक, वाचन या AI सामग्री के आधार पर लिए गए किसी भी निर्णय, कार्य या परिणाम के लिए ज्योतिष जिम्मेदार नहीं है। हमारा कुल दायित्व आपके द्वारा भुगतान की गई राशि तक सीमित है।" },
      { heading: "आर्य कैसे बात करती हैं (टोन और क्या उम्मीद करें)", body: "आर्य को गर्मजोशी, बातचीत और व्यक्तिगत तरीके से बात करने के लिए डिज़ाइन किया गया है — भरोसेमंद दोस्त या बड़े जैसा, औपचारिक रिपोर्ट नहीं। क्योंकि सेवा मनोरंजन, आराम और आत्म-चिंतन के लिए है, वह भावनात्मक विषयों (प्रेम, शादी, परिवार, भावनाएँ) पर उत्साहवर्धक, अभिव्यंजक और स्पष्ट हो सकती है। यह लहजा जानबूझकर है और सेवा का हिस्सा है। ज्योतिष उपयोग करने से आप स्वीकार करते हैं कि आर्य की बातचीत की शैली — व्यक्तिगत विषयों पर गर्मजोशी से बात करना — वही है जिसके लिए आपने साइन अप किया है, और आप यह ज़िम्मेदारी लेते हैं कि आप क्या साझा करते हैं और बातों पर कैसे कार्य करते हैं। आप किसी भी समय चैट समाप्त कर सकते हैं या सेवा बंद कर सकते हैं। यह पेशेवर सलाह नहीं है, और हर वाचन AI-जनित व्याख्या है, तथ्य नहीं (ऊपर के अनुभाग देखें)।" },
      { heading: "क्षतिपूर्ति", body: "आप ज्योतिष और उसके मालिकों, अधिकारियों, कर्मचारियों और एजेंटों को आपके सेवा उपयोग, इन नियमों के उल्लंघन, या सेवा के दुरुपयोग से उत्पन्न किसी भी दावे, हानि, क्षति या लागत (कानूनी शुल्क सहित) से क्षतिपूर्ति करने और हानि-रहित रखने के लिए सहमत हैं।" },
      { heading: "लागू कानून और अधिकार क्षेत्र", body: "ये नियम भारत के कानूनों द्वारा शासित हैं। इन नियमों से उत्पन्न कोई भी विवाद मध्यस्थता और सुलह अधिनियम, 1996 के तहत नई दिल्ली में एक एकल मध्यस्थ के समक्ष मध्यस्थता द्वारा हल किया जाएगा, और पुरस्कार अंतिम और बाध्यकारी होगा। आप किसी भी अंतरिम राहत या मध्यस्थता के अधीन नहीं होने वाले मामलों के लिए नई दिल्ली की अदालतों के अनन्य अधिकार क्षेत्र के अधीन हैं।" },
      { heading: "बदलाव व संपर्क", body: "हम इन नियमों को अपडेट कर सकते हैं। बदलाव के बाद उपयोग का मतलब स्वीकृति है। सवाल: support@aijothis.com।" },
    ],
  },
  mr: {
    title: "अटी व शर्ती",
    lastUpdated: "शेवटचे अपडेट: ७ ऑगस्ट २०२६",
    intro: "ज्योतिष वापरल्याने तुम्ही या अटींना सहमत होता. कृपया काळजीपूर्वक वाचा — विशेषतः AI-निर्मित सामग्री आणि आर्य माणूस नाही याबद्दल.",
    sections: [
      { heading: "संकट आणि आपत्कालीन सूचना", body: "जर तुम्ही स्वतःला किंवा इतरांना इजा करण्याचा विचार करत असाल, किंवा तुम्हाला वाटत असेल की दुसरी व्यक्ती धोक्यात आहे, किंवा तुम्हाला वैद्यकीय आपत्कालीन स्थिती असेल — सेवेचा वापर त्वरित थांबवा आणि लगेच पोलिसांशी (भारतात 112) किंवा आत्महत्या प्रतिबंध हेल्पलाइन जसे AASRA (91-22-27546669), KIRAN (1800-599-0019) किंवा iCall (9152987821) यांच्याशी संपर्क साधा. प्लॅटफॉर्म यापैकी कोणत्याही परिस्थितीत वापरण्यासाठी बनवलेला नाही आणि आवश्यक मदत देऊ शकत नाही. जर तुम्ही अशा परिस्थितीत सेवा वापरणे सुरू ठेवले तर ते पूर्णपणे तुमच्या स्वतःच्या जोखमीवर आहे." },
      { heading: "सेवा", body: "ज्योतिष हे AI वैदिक ज्योतिष ॲप आहे. ते तुमच्या जन्म माहितीवरून तुमची कुंडली बनवते आणि आर्य (AI ज्योतिषी) मार्फत वैयक्तिक वाचन आणि चॅट उत्तरे देते. आर्य हा आर्टिफिशियल इंटेलिजन्स (संगणक प्रोग्राम) आहे, माणूस नाही. सेवा मनोरंजन, स्व-चिंतन आणि वैयक्तिक माहितीसाठी आहे." },
      { heading: "AI-निर्मित सामग्री", body: "आर्य जे काही बोलतो ते आर्टिफिशियल इंटेलिजन्सने तयार होते. AI चुका करू शकतो — वाचन चुकीचे, अपूर्ण किंवा जुने असू शकते. तुमचे वाचन दाखवण्यापूर्वी कोणीही माणूस त्याचे पुनरावलोकन करत नाही. सर्व आउटपुट AI-निर्मित संदर्भ साहित्य समजा — सत्यापित किंवा हमी दिलेली माहिती नाही." },
      { heading: "व्यावसायिक सल्ला नाही", body: "वाचन व्यावसायिक सल्ला नाही. ते डॉक्टर, वकील, आर्थिक सल्लागार, नाते-सल्लागार किंवा मानसिक आरोग्य तज्ञांच्या सल्ल्याचा पर्याय नाही. महत्त्वाचे जीवन निर्णय — लग्न, करिअर, पैसा, आरोग्य, कुटुंब — केवळ आर्यच्या शब्दांवर घेऊ नका. नेहमी खऱ्या माणसातील तज्ञाचा सल्ला घ्या. सेवा वैद्यकीय निदानासाठी किंवा तुमच्यासाठी कोणते औषध किंवा उपचार योग्य आहे हे सांगण्यासाठी नाही — सेवेद्वारे दिलेला असा कोणताही सल्ला दुर्लक्ष करा. आर्यकडून मिळालेल्या माहितीमुळे तुमच्या डॉक्टरकडून किंवा पात्र व्यावसायिकाकडून व्यक्तिगत (in-person) काळजी घेण्यास उशीर, टाळाटाळ किंवा दुर्लक्ष करू नका." },
      { heading: "सिस्टम-निर्मित सल्ला", body: "सर्व वाचन, चॅट उत्तरे आणि भविष्यवाण्या इंटरॅक्टिव AI टूल (आर्य) द्वारे सिस्टम-निर्मित आहेत आणि फक्त सामान्य माहिती आणि मनोरंजनासाठी आहेत. त्या व्यावसायिक, वैद्यकीय, कायदेशीर, आर्थिक किंवा विशेष सल्ला नाहीत. कोणत्याही सिस्टम-निर्मित सल्ल्याच्या अचूकतेची, पूर्णतेची किंवा उपयुक्ततेची आम्ही हमी देत नाही. आर्यच्या आउटपुटवर कोणताही विश्वास पूर्णपणे तुमच्या स्वतःच्या जोखमीवर आहे, आणि त्यावर आधारित कोणताही निर्णय घेण्यापूर्वी तुम्हाला पात्र व्यावसायिकांचा सल्ला घेण्यास प्रोत्साहित केले जाते." },
      { heading: "तुमची जबाबदारी", body: "तुम्ही तुमच्या निर्णयांसाठी स्वतः जबाबदार आहात. तुम्ही स्वखर्चाने सेवा वापरता आणि वाचन वस्तुस्थिती नाही मानण्यास सहमत आहात. जर तुम्ही संकटात असाल किंवा स्व-हानीचा विचार करत असाल, तर विश्वासू व्यक्तीशी किंवा मानसिक आरोग्य तज्ञाशी संपर्क साधा (भारतात: KIRAN 1800-599-0019, किंवा iCall 9152987821)." },
      { heading: "खाती", body: "तुम्ही खात्याशिवाय सेवा वापरू शकता, किंवा Google ने login करू शकता. वय किमान १८ वर्षे असावे आणि तुम्ही भारतीय करार अधिनियम, १८७२ अंतर्गत कायदेशीररित्या बंधनकारक करार करण्यास सक्षम असाल. जन्म माहिती अचूक असावी — आम्ही त्यावरून तुमची कुंडली बनवतो." },
      { heading: "पेमेंट व रिफंड", body: "Question packs एकदाची, न-आवर्ती खरेदी आहेत. पेमेंट Razorpay द्वारे होते. खरेदीच्या ७ दिवसांत रिफंड फक्त questions पूर्णपणे न वापरले असल्यासच उपलब्ध. कोणत्याही वाचन, भविष्यवाणी किंवा सल्ल्याच्या अचूकतेसाठी किंवा उपयुक्ततेसाठी रिफंड दिला जात नाही — ज्योतिष व्याख्यात्मक आहे, वस्तुस्थिती नाही, आणि कोणत्याही सल्ल्याच्या तथ्यात्मक अचूकतेची जबाबदारी आम्ही घेत नाही." },
      { heading: "योग्य वापर", body: "सेवेचा गैरवापर करू नका — आक्षेपार्ह, मानहानिकारक, छळ करणारी किंवा बेकायदेशीर सामग्री नाही; सेवेला हानी, व्यत्यय किंवा अनधिकृत प्रवेशाचे प्रयत्न नाही; दुसऱ्याच्या खात्याचा किंवा तपशिलांचा वापर नाही; प्रति व्यक्ती एकापेक्षा जास्त खाते नाही. सेवा काळे जादू, मांत्रिक, वूडू, तांत्रिक पद्धती किंवा इतरांना हानी यांची सुविधा देत नाही. कोणत्याही गैरवापराची माहिती support@aijothis.com वर द्या. नियम मोडल्यास खाती निलंबित होऊ शकतात." },
      { heading: "हमी नाही", body: "ज्योतिष व्याख्यात्मक आहे, वस्तुस्थिती नाही. आम्ही कोणत्याही वाचन, भविष्यवाणी किंवा कालावधीच्या अचूकतेची हमी देत नाही आणि भविष्यातील घटनांचे वचन देत नाही. भविष्यवाण्या सूचना आहेत, निश्चितता नाही." },
      { heading: "स्वीकृती", body: "ज्योतिष वापरल्याने तुम्ही कबूल करता की तुम्हाला समजते: (अ) आर्य हा AI आहे, माणूस नाही; (ब) सर्व सामग्री AI-निर्मित आहे आणि चुकीची असू शकते; (क) सेवा मनोरंजन आणि संदर्भासाठी आहे; (ड) ती व्यावसायिक सल्ला नाही; आणि (इ) तुम्ही त्यावर महत्त्वाचे जीवन निर्णय घेणार नाही." },
      { heading: "जबाबदारी", body: "कायद्याने परवानगी असलेल्या कमाल मर्यादेपर्यंत, वाचन किंवा AI सामग्रीवर आधारित कोणत्याही निर्णय, कृती किंवा परिणामासाठी ज्योतिष जबाबदार नाही. आमची एकूण जबाबदारी तुम्ही भरलेल्या रकमेपर्यंत मर्यादित." },
      { heading: "आर्य कशी बोलते (टोन आणि काय अपेक्षा करावी)", body: "आर्य उबदार, संवादात्मक आणि वैयक्तिक पद्धतीने बोलण्यासाठी डिझाइन केली आहे — विश्वासू मित्र किंवा मोठ्या व्यक्तीसारखी, औपचारिक अहवाल नाही. कारण सेवा मनोरंजन, दिलासा आणि स्व-चिंतनासाठी आहे, ती भावनिक विषयांवर (प्रेम, लग्न, कुटुंब, भावना) प्रोत्साहक, व्यक्त होणारी आणि थेट असू शकते. हा टोन जाणूनबुजून आहे आणि सेवेचा भाग आहे. ज्योतिष वापरल्याने तुम्ही मान्य करता की आर्यची संभाषणशैली — वैयक्तिक विषयांवर उबदार बोलणे — तुम्ही निवडलेला अनुभव आहे, आणि काय सामायिक करता व त्यावर कसे कृती करता याची जबाबदारी तुमची आहे. तुम्ही कधीही चॅट संपवू शकता किंवा सेवा थांबवू शकता. हे व्यावसायिक सल्ला नाही, आणि प्रत्येक वाचन AI-निर्मित व्याख्या आहे, वस्तुस्थिती नाही (वरील विभाग पहा)." },
      { heading: "क्षतिपूर्ती", body: "तुम्ही ज्योतिष आणि त्याचे मालक, अधिकारी, कर्मचारी आणि एजंट यांना तुमच्या सेवा वापरामुळे, या अटींच्या उल्लंघनामुळे किंवा सेवेच्या गैरवापरामुळे उद्भवलेल्या कोणत्याही दाव्यांपासून, नुकसानापासून, हानीपासून किंवा खर्चापासून (कायदेशीर शुल्कासह) संरक्षण देण्यास आणि हानी-मुक्त ठेवण्यास सहमत आहात." },
      { heading: "लागू कायदा आणि अधिकारक्षेत्र", body: "या अटी भारताच्या कायद्यांद्वारे शासित आहेत. या अटींमधून उद्भवलेला कोणताही विवाद मध्यस्थी आणि सुलभीकरण अधिनियम, १९९६ अंतर्गत नवी दिल्ली येथे एका एकल मध्यस्थासमोर मध्यस्थीद्वारे सोडवला जाईल, आणि निर्णय अंतिम आणि बंधनकारक असेल. कोणत्याही तात्पुरत्या दिलास्यासाठी किंवा मध्यस्थीच्या कक्षेत न येणाऱ्या बाबींसाठी तुम्ही नवी दिल्लीच्या न्यायालयांच्या अनन्य अधिकारक्षेत्राच्या अधीन आहात." },
      { heading: "बदल व संपर्क", body: "आम्ही या अटी अपडेट करू शकतो. बदलानंतर वापर म्हणजे स्वीकृती. प्रश्न: support@aijothis.com." },
    ],
  },
};
