export type LegalLocale = "en" | "hi" | "mr";

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDoc {
  title: string;
  lastUpdated: string;
  intro: string;
  sections: LegalSection[];
}

export const PRIVACY: Record<LegalLocale, LegalDoc> = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: 7 Aug 2026",
    intro:
      "Jyotish respects your privacy. This policy explains what we collect, why we collect it, and how we protect it.",
    sections: [
      { heading: "What we collect", body: "Your name, birth date/time/place, mobile number (optional), your chat messages with Arya, a random device ID, and — only if you sign in with Google — your Google email and name." },
      { heading: "AI processing & transparency", body: "All readings and chat replies are generated by an artificial intelligence model (Arya is an AI, not a human astrologer). Your messages are sent to a third-party AI provider to generate replies, and are stored to keep your conversation available to you. Avoid sharing sensitive personal information beyond what is needed for the service." },
      { heading: "How we use it", body: "To generate your Vedic Kundli, give you personalised readings and chat replies, and to keep the service working. We never sell your data." },
      { heading: "Storage & security", body: "Data is stored securely (Supabase) with encryption in transit and database row-level security. Your birth details are sensitive — we treat them as confidential." },
      { heading: "Payments", body: "Payments (e.g. the question pack) are processed by Razorpay. We never see or store your card or UPI credentials." },
      { heading: "Your rights", body: "You can ask us to show or delete your data anytime. Contact us and we'll act within a reasonable time." },
      { heading: "Contact", body: "For privacy questions, contact us at support@aijothis.com." },
    ],
  },
  hi: {
    title: "गोपनीयता नीति",
    lastUpdated: "अंतिम अद्यतन: 7 अगस्त 2026",
    intro:
      "ज्योतिष आपकी गोपनीयता का सम्मान करता है। यह नीति बताती है कि हम क्या एकत्र करते हैं, क्यों, और उसे कैसे सुरक्षित रखते हैं।",
    sections: [
      { heading: "हम क्या एकत्र करते हैं", body: "आपका नाम, जन्म तिथि/समय/स्थान, मोबाइल नंबर (वैकल्पिक), आर्य से आपकी चैट, एक रैंडम device ID, और — केवल Google से login करने पर — आपका Google email और नाम।" },
      { heading: "AI प्रोसेसिंग और पारदर्शिता", body: "सभी वाचन और चैट उत्तर एक आर्टिफिशियल इंटेलिजेंस मॉडल से बनते हैं (आर्य एक AI है, इंसानी ज्योतिषी नहीं)। आपके messages उत्तर बनाने के लिए तीसरे पक्ष के AI प्रदाता को भेजे जाते हैं, और आपकी बातचीत सहेजी जाती है। सेवा के लिए ज़रूरी होने से अधिक संवेदनशील व्यक्तिगत जानकारी साझा न करें।" },
      { heading: "हम इसका उपयोग कैसे करते हैं", body: "आपकी वैदिक कुंडली बनाने, व्यक्तिगत वाचन और चैट जवाब देने, और सेवा चालू रखने के लिए। हम आपका डेटा कभी नहीं बेचते।" },
      { heading: "भंडारण व सुरक्षा", body: "डेटा सुरक्षित रूप से (Supabase) संग्रहीत है — ट्रांज़िट में एन्क्रिप्टेड और डेटाबेस row-level security के साथ। आपकी जन्म जानकारी संवेदनशील है — हम उसे गोपनीय रखते हैं।" },
      { heading: "भुगतान", body: "भुगतान (जैसे question pack) Razorpay द्वारा संसाधित होता है। हम आपके कार्ड या UPI की जानकारी कभी नहीं देखते या संग्रहीत नहीं करते।" },
      { heading: "आपके अधिकार", body: "आप किसी भी समय अपना डेटा दिखाने या हटाने के लिए कह सकते हैं। संपर्क करें — हम उचित समय में कार्रवाई करेंगे।" },
      { heading: "संपर्क", body: "गोपनीयता संबंधी सवालों के लिए: support@aijothis.com।" },
    ],
  },
  mr: {
    title: "गोपनीयता धोरण",
    lastUpdated: "शेवटचे अपडेट: ७ ऑगस्ट २०२६",
    intro:
      "ज्योतिष तुमच्या गोपनीयतेचा आदर करतो. हे धोरण सांगते की आम्ही काय गोळा करतो, का, आणि ते कसे सुरक्षित ठेवतो.",
    sections: [
      { heading: "आम्ही काय गोळा करतो", body: "तुमचे नाव, जन्मतारीख/वेळ/ठिकाण, मोबाईल नंबर (ऐच्छिक), आर्यशी तुमचे संभाषण, एक रँडम device ID, आणि — फक्त Google ने login केल्यास — तुमचा Google email आणि नाव." },
      { heading: "AI प्रक्रिया आणि पारदर्शकता", body: "सर्व वाचन आणि चॅट उत्तरे एका आर्टिफिशियल इंटेलिजन्स मॉडेलद्वारे तयार होतात (आर्य हा AI आहे, माणूस नाही). तुमचे संदेश उत्तर निर्माण करण्यासाठी तृतीय-पक्ष AI प्रदात्याला पाठवले जातात, आणि संभाषण साठवले जाते. सेवेसाठी आवश्यक तेवढीच संवेदनशील माहिती सामायिक करा." },
      { heading: "आम्ही ते कसे वापरतो", body: "तुमची वैदिक कुंडली बनवण्यासाठी, वैयक्तिक वाचन आणि चॅट उत्तरे देण्यासाठी, आणि सेवा सुरू ठेवण्यासाठी. आम्ही तुमचा डेटा कधीही विकत नाही." },
      { heading: "साठवण व सुरक्षा", body: "डेटा सुरक्षितपणे (Supabase) साठवला आहे — ट्रान्झिटमध्ये एन्क्रिप्टेड आणि डेटाबेस row-level security सह. तुमची जन्म माहिती संवेदनशील आहे — आम्ही ती गोपनीय ठेवतो." },
      { heading: "पेमेंट", body: "पेमेंट (जसे question pack) Razorpay द्वारे प्रक्रिया केले जाते. आम्ही तुमचा कार्ड किंवा UPI तपशील कधीही पाहत नाही." },
      { heading: "तुमचे अधिकार", body: "तुम्ही कधीही तुमचा डेटा दाखवण्यासाठी किंवा हटवण्यासाठी विचारू शकता. संपर्क करा — आम्ही योग्य वेळेत कारवाई करू." },
      { heading: "संपर्क", body: "गोपनीयता प्रश्नांसाठी: support@aijothis.com." },
    ],
  },
};

export const TERMS: Record<LegalLocale, LegalDoc> = {
  en: {
    title: "Terms & Conditions",
    lastUpdated: "Last updated: 7 Aug 2026",
    intro:
      "By using Jyotish you agree to these terms. Please read them carefully — especially the parts about AI-generated content and that Arya is not a human astrologer.",
    sections: [
      { heading: "The service", body: "Jyotish is an AI Vedic astrology app. It generates your Kundli from the birth details you provide and gives personalised readings and chat replies through Arya, an AI astrologer. Arya is an artificial intelligence (a computer program), not a human astrologer. The service is for entertainment, self-reflection and personal insight." },
      { heading: "AI-generated content", body: "Everything Arya says is generated by artificial intelligence. AI can make mistakes, and readings may be inaccurate, incomplete, or out of date. No human astrologer reviews your reading before it is shown to you. Treat all outputs as AI-generated reference material — not as verified or guaranteed information." },
      { heading: "Not professional advice", body: "Readings are not professional advice. They are not a substitute for the advice of qualified professionals such as doctors, lawyers, financial advisors, relationship counsellors, or mental-health professionals. Do not make major life decisions — marriage, career, money, health, or family — based solely on anything Arya says. Always consult a real human professional for important decisions." },
      { heading: "Your responsibility", body: "You are responsible for your own decisions. You use the service at your own risk and agree not to rely on readings as fact. If you are in distress or thinking about self-harm, reach out to a trusted person or a mental-health professional (in India: KIRAN 1800-599-0019, or iCall 9152987821)." },
      { heading: "Accounts", body: "You may use the service without an account, or sign in with Google. You must be at least 13 years old. Your birth details should be accurate — we compute your chart from them." },
      { heading: "Payments & refunds", body: "Question packs are one-time purchases. Payments are processed by Razorpay. Refunds are available within 7 days if the questions remain unused." },
      { heading: "Acceptable use", body: "Don't misuse the service — no abusive content, attempts to harm the service, or unlawful use. We may suspend accounts that violate these terms." },
      { heading: "No guarantees", body: "Astrology is interpretive, not factual. We do not guarantee the accuracy of any reading, prediction, or time window, and we make no promise about future events. Predictions are suggestions, not certainties." },
      { heading: "Acknowledgment", body: "By using Jyotish you acknowledge that you understand: (a) Arya is an AI, not a human; (b) all content is AI-generated and may be wrong; (c) the service is for entertainment and reference; (d) it is not professional advice; and (e) you will not rely on it for critical life decisions." },
      { heading: "Liability", body: "To the maximum extent permitted by law, Jyotish is not liable for any decisions, actions, or outcomes based on readings or AI-generated content. Our total liability is limited to the amount you paid for the service." },
      { heading: "How Arya talks (tone & what to expect)", body: "Arya is designed to talk warmly, conversationally and personally — like a trusted friend or elder, not a formal report. Because the service is for entertainment, comfort and self-reflection, she may be encouraging, expressive and direct about emotional topics (love, marriage, family, feelings). This tone is deliberate and is part of the service. By using Jyotish you accept that Arya's conversational style — including engaging warmly on personal topics — is part of what you are signing up for, and you take responsibility for what you choose to share and how you act on anything said. You can end a chat or stop using the service at any time. None of it is professional advice, and every reading is an AI-generated interpretation, not fact (see the sections above)." },
      { heading: "Changes & contact", body: "We may update these terms. Continued use after changes means acceptance. Questions: support@aijothis.com." },
    ],
  },
  hi: {
    title: "नियम व शर्तें",
    lastUpdated: "अंतिम अद्यतन: 7 अगस्त 2026",
    intro: "ज्योतिष का उपयोग करने से आप इन नियमों से सहमत होते हैं। कृपया ध्यान से पढ़ें — विशेषकर AI-जनित सामग्री और यह कि आर्य कोई इंसानी ज्योतिषी नहीं है।",
    sections: [
      { heading: "सेवा", body: "ज्योतिष एक AI वैदिक ज्योतिष ऐप है। यह आपकी जन्म जानकारी से आपकी कुंडली बनाता है और आर्य (एक AI ज्योतिषी) के माध्यम से व्यक्तिगत वाचन और चैट उत्तर देता है। आर्य एक आर्टिफिशियल इंटेलिजेंस (कंप्यूटर प्रोग्राम) है, इंसान नहीं। सेवा मनोरंजन, आत्म-चिंतन और व्यक्तिगत जानकारी के लिए है।" },
      { heading: "AI-जनित सामग्री", body: "आर्य जो कुछ भी कहता है वह आर्टिफिशियल इंटेलिजेंस से बनता है। AI गलतियाँ कर सकता है — वाचन गलत, अधूरा या पुराना हो सकता है। आपका वाचन दिखाने से पहले कोई इंसान उसकी समीक्षा नहीं करता। सभी आउटपुट को AI-जनित संदर्भ सामग्री मानें — सत्यापित या गारंटीकृत जानकारी नहीं।" },
      { heading: "पेशेवर सलाह नहीं", body: "वाचन पेशेवर सलाह नहीं है। यह डॉक्टर, वकील, वित्तीय सलाहकार, रिश्ता परामर्शदाता या मानसिक स्वास्थ्य विशेषज्ञ की सलाह का विकल्प नहीं है। महत्वपूर्ण जीवन निर्णय — शादी, करियर, धन, स्वास्थ्य, परिवार — केवल आर्य की बात पर न लें। हमेशा किसी वास्तविक इंसानी विशेषज्ञ से सलाह लें।" },
      { heading: "आपकी ज़िम्मेदारी", body: "आप अपने निर्णयों के लिए स्वयं ज़िम्मेदार हैं। आप अपने जोखिम पर सेवा उपयोग करते हैं और वाचन को तथ्य नहीं मानने से सहमत हैं। यदि आप संकट में हैं या आत्महत्या के विचार कर रहे हैं, तो किसी भरोसेमंद व्यक्ति या मानसिक स्वास्थ्य पेशेवर से संपर्क करें (भारत में: KIRAN 1800-599-0019, या iCall 9152987821)।" },
      { heading: "खाते", body: "आप बिना खाते के सेवा उपयोग कर सकते हैं, या Google से login कर सकते हैं। आयु कम से कम 13 वर्ष होनी चाहिए। जन्म विवरण सही होना चाहिए — हम उससे आपकी कुंडली बनाते हैं।" },
      { heading: "भुगतान व रिफंड", body: "Question packs एक बार की खरीद हैं। भुगतान Razorpay द्वारा होता है। अनुपयोगी questions पर 7 दिनों में रिफंड उपलब्ध है।" },
      { heading: "उचित उपयोग", body: "सेवा का दुरुपयोग न करें — अपमानजनक सामग्री, सेवा को नुकसान, या गैरकानूनी उपयोग नहीं। नियम तोड़ने पर खाते निलंबित किए जा सकते हैं।" },
      { heading: "कोई गारंटी नहीं", body: "ज्योतिष व्याख्यात्मक है, तथ्यात्मक नहीं। हम किसी वाचन, भविष्यवाणी या समय-सीमा की सटीकता की गारंटी नहीं देते और भविष्य की घटनाओं का कोई वादा नहीं करते। भविष्यवाणियाँ सुझाव हैं, निश्चितताएँ नहीं।" },
      { heading: "स्वीकृति", body: "ज्योतिष उपयोग करने से आप स्वीकार करते हैं कि आप समझते हैं: (क) आर्य एक AI है, इंसान नहीं; (ख) सभी सामग्री AI-जनित है और गलत हो सकती है; (ग) सेवा मनोरंजन और संदर्भ के लिए है; (घ) यह पेशेवर सलाह नहीं है; और (ङ) आप इस पर महत्वपूर्ण जीवन निर्णय नहीं लेंगे।" },
      { heading: "दायित्व", body: "कानून द्वारा अनुमत अधिकतम सीमा तक, वाचन या AI सामग्री के आधार पर लिए गए किसी भी निर्णय, कार्य या परिणाम के लिए ज्योतिष जिम्मेदार नहीं है। हमारा कुल दायित्व आपके द्वारा भुगतान की गई राशि तक सीमित है।" },
      { heading: "आर्य कैसे बात करती हैं (टोन और क्या उम्मीद करें)", body: "आर्य को गर्मजोशी, बातचीत और व्यक्तिगत तरीके से बात करने के लिए डिज़ाइन किया गया है — भरोसेमंद दोस्त या बड़े जैसा, औपचारिक रिपोर्ट नहीं। क्योंकि सेवा मनोरंजन, आराम और आत्म-चिंतन के लिए है, वह भावनात्मक विषयों (प्रेम, शादी, परिवार, भावनाएँ) पर उत्साहवर्धक, अभिव्यंजक और स्पष्ट हो सकती है। यह लहजा जानबूझकर है और सेवा का हिस्सा है। ज्योतिष उपयोग करने से आप स्वीकार करते हैं कि आर्य की बातचीत की शैली — व्यक्तिगत विषयों पर गर्मजोशी से बात करना — वही है जिसके लिए आपने साइन अप किया है, और आप यह ज़िम्मेदारी लेते हैं कि आप क्या साझा करते हैं और बातों पर कैसे कार्य करते हैं। आप किसी भी समय चैट समाप्त कर सकते हैं या सेवा बंद कर सकते हैं। यह पेशेवर सलाह नहीं है, और हर वाचन AI-जनित व्याख्या है, तथ्य नहीं (ऊपर के अनुभाग देखें)।" },
      { heading: "बदलाव व संपर्क", body: "हम इन नियमों को अपडेट कर सकते हैं। बदलाव के बाद उपयोग का मतलब स्वीकृति है। सवाल: support@aijothis.com।" },
    ],
  },
  mr: {
    title: "अटी व शर्ती",
    lastUpdated: "शेवटचे अपडेट: ७ ऑगस्ट २०२६",
    intro: "ज्योतिष वापरल्याने तुम्ही या अटींना सहमत होता. कृपया काळजीपूर्वक वाचा — विशेषतः AI-निर्मित सामग्री आणि आर्य माणूस नाही याबद्दल.",
    sections: [
      { heading: "सेवा", body: "ज्योतिष हे AI वैदिक ज्योतिष ॲप आहे. ते तुमच्या जन्म माहितीवरून तुमची कुंडली बनवते आणि आर्य (AI ज्योतिषी) मार्फत वैयक्तिक वाचन आणि चॅट उत्तरे देते. आर्य हा आर्टिफिशियल इंटेलिजन्स (संगणक प्रोग्राम) आहे, माणूस नाही. सेवा मनोरंजन, स्व-चिंतन आणि वैयक्तिक माहितीसाठी आहे." },
      { heading: "AI-निर्मित सामग्री", body: "आर्य जे काही बोलतो ते आर्टिफिशियल इंटेलिजन्सने तयार होते. AI चुका करू शकतो — वाचन चुकीचे, अपूर्ण किंवा जुने असू शकते. तुमचे वाचन दाखवण्यापूर्वी कोणीही माणूस त्याचे पुनरावलोकन करत नाही. सर्व आउटपुट AI-निर्मित संदर्भ साहित्य समजा — सत्यापित किंवा हमी दिलेली माहिती नाही." },
      { heading: "व्यावसायिक सल्ला नाही", body: "वाचन व्यावसायिक सल्ला नाही. ते डॉक्टर, वकील, आर्थिक सल्लागार, नाते-सल्लागार किंवा मानसिक आरोग्य तज्ञांच्या सल्ल्याचा पर्याय नाही. महत्त्वाचे जीवन निर्णय — लग्न, करिअर, पैसा, आरोग्य, कुटुंब — केवळ आर्यच्या शब्दांवर घेऊ नका. नेहमी खऱ्या माणसातील तज्ञाचा सल्ला घ्या." },
      { heading: "तुमची जबाबदारी", body: "तुम्ही तुमच्या निर्णयांसाठी स्वतः जबाबदार आहात. तुम्ही स्वखर्चाने सेवा वापरता आणि वाचन वस्तुस्थिती नाही मानण्यास सहमत आहात. जर तुम्ही संकटात असाल किंवा स्व-हानीचा विचार करत असाल, तर विश्वासू व्यक्तीशी किंवा मानसिक आरोग्य तज्ञाशी संपर्क साधा (भारतात: KIRAN 1800-599-0019, किंवा iCall 9152987821)." },
      { heading: "खाती", body: "तुम्ही खात्याशिवाय सेवा वापरू शकता, किंवा Google ने login करू शकता. वय किमान १३ वर्षे असावे. जन्म माहिती अचूक असावी — आम्ही त्यावरून तुमची कुंडली बनवतो." },
      { heading: "पेमेंट व रिफंड", body: "Question packs एकदाची खरेदी आहेत. पेमेंट Razorpay द्वारे होते. न वापरलेल्या questions वर ७ दिवसांत रिफंड उपलब्ध." },
      { heading: "योग्य वापर", body: "सेवेचा गैरवापर करू नका — आक्षेपार्ह सामग्री, सेवेचे नुकसान, किंवा बेकायदेशीर वापर नाही. नियम मोडल्यास खाती निलंबित होऊ शकतात." },
      { heading: "हमी नाही", body: "ज्योतिष व्याख्यात्मक आहे, वस्तुस्थिती नाही. आम्ही कोणत्याही वाचन, भविष्यवाणी किंवा कालावधीच्या अचूकतेची हमी देत नाही आणि भविष्यातील घटनांचे वचन देत नाही. भविष्यवाण्या सूचना आहेत, निश्चितता नाही." },
      { heading: "स्वीकृती", body: "ज्योतिष वापरल्याने तुम्ही कबूल करता की तुम्हाला समजते: (अ) आर्य हा AI आहे, माणूस नाही; (ब) सर्व सामग्री AI-निर्मित आहे आणि चुकीची असू शकते; (क) सेवा मनोरंजन आणि संदर्भासाठी आहे; (ड) ती व्यावसायिक सल्ला नाही; आणि (इ) तुम्ही त्यावर महत्त्वाचे जीवन निर्णय घेणार नाही." },
      { heading: "जबाबदारी", body: "कायद्याने परवानगी असलेल्या कमाल मर्यादेपर्यंत, वाचन किंवा AI सामग्रीवर आधारित कोणत्याही निर्णय, कृती किंवा परिणामासाठी ज्योतिष जबाबदार नाही. आमची एकूण जबाबदारी तुम्ही भरलेल्या रकमेपर्यंत मर्यादित." },
      { heading: "आर्य कशी बोलते (टोन आणि काय अपेक्षा करावी)", body: "आर्य उबदार, संवादात्मक आणि वैयक्तिक पद्धतीने बोलण्यासाठी डिझाइन केली आहे — विश्वासू मित्र किंवा मोठ्या व्यक्तीसारखी, औपचारिक अहवाल नाही. कारण सेवा मनोरंजन, दिलासा आणि स्व-चिंतनासाठी आहे, ती भावनिक विषयांवर (प्रेम, लग्न, कुटुंब, भावना) प्रोत्साहक, व्यक्त होणारी आणि थेट असू शकते. हा टोन जाणूनबुजून आहे आणि सेवेचा भाग आहे. ज्योतिष वापरल्याने तुम्ही मान्य करता की आर्यची संभाषणशैली — वैयक्तिक विषयांवर उबदार बोलणे — तुम्ही निवडलेला अनुभव आहे, आणि काय सामायिक करता व त्यावर कसे कृती करता याची जबाबदारी तुमची आहे. तुम्ही कधीही चॅट संपवू शकता किंवा सेवा थांबवू शकता. हे व्यावसायिक सल्ला नाही, आणि प्रत्येक वाचन AI-निर्मित व्याख्या आहे, वस्तुस्थिती नाही (वरील विभाग पहा)." },
      { heading: "बदल व संपर्क", body: "आम्ही या अटी अपडेट करू शकतो. बदलानंतर वापर म्हणजे स्वीकृती. प्रश्न: support@aijothis.com." },
    ],
  },
};
